(($) ->
  'use strict'
  $(document).ready ->
    # PARALLAX BACKGROUNDS FOR DESKTOPS

    hideMenu = ->
      if menu.is(':hidden')
        menu.removeAttr 'style'
      return

    if $(this).width() > 768
      $(window).stellar horizontalScrolling: false
    $('#navigation').headroom()
   
   # MOBILE NAVIGATION MENU DROPDOWN
    menu = $('#navigation-menu')
    menuToggle = $('#js-mobile-menu')
    menuLink = $('.navigation .nav-link a')
    $(menuToggle).on 'click', (e) ->
      e.preventDefault()
      menu.slideToggle ->
        hideMenu()
        return
      return
    $(menuLink).on 'click', ->
      if $('.navigation-menu-button').css('display') == 'block'
        menu.slideToggle ->
          hideMenu()
          return
      return
    
    # ADD ACTIVE CLASS TO NAVIGATION ITEM WHEN CLICKED
    $('.navigation a').on 'click', ->
      $('.navigation li').removeClass 'active'
      $(this).closest('li').addClass 'active'
      return
    
    # SMOOTH SCROLLING BETWEEN SECTIONS 
    $('a[href*=#section-]').on 'click', ->
      navHeight = $('header#navigation').height()
      top = $(document).scrollTop()
      if location.pathname.replace(/^\//, '') == @pathname.replace(/^\//, '') or location.hostname == @hostname
        target = $(@hash)
        target = if target.length then target else $('[name=' + @hash.slice(1) + ']')
        if target.length
          if $(@hash).offset().top < top
            # scroll position includes nav height
            $('html,body').animate { scrollTop: target.offset().top - navHeight }, 600
            return false
          else
            # scroll position without nav height
            $('html,body').animate { scrollTop: target.offset().top + 2 }, 600
            return false
      return
    
    # RESPONSIVE VIDEOS - FITVIDS
    $('.fitvids').fitVids()
    
    # OWL CAROUSEL SLIDERS
    $('#showcase-slider, #quote-slider').owlCarousel
      items: 1
      loop: true
      autoplay: true
      autoplayTimeout: 4000
    $('#blog-teasers').owlCarousel
      items: 3
      video: true
      autoplay: true
      autoplayTimeout: 4000
      autoplayHoverPause: true
      responsive:
        1: items: 1
        540: items: 2
        767: items: 3
    # FLEXSLIDER
    $('#gallery-slider').flexslider()
    # NEWSLETTER SIGNUP
    $('#newsletter').submit ->
      str = $(this).serialize()
      $.ajax
        type: 'POST'
        url: 'php/newsletter.php'
        data: str
        success: (msg) ->
          result = ''
          if msg == 'OK'
            result = '<div class="form-feedback form-success">Subscription sent!</div>'
          else
            result = msg
          $('#newsletter-error').html result
          return
      false
    # CONTACT FORM SUBMISSION
    $('#contact-form').submit ->
      str = $(this).serialize()
      $.ajax
        type: 'POST'
        url: 'php/contact.php'
        data: str
        success: (msg) ->
          result = ''
          if msg == 'OK'
            result = '<div class="form-feedback form-success">All good, message sent!</div>'
            $('input[type="submit"]').hide()
          else
            result = msg
          $('#contact-error').html result
          return
      false
    # END OF SCRIPTS
    return
  return
) jQuery

# ---
# generated by js2coffee 2.1.0